server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/renaldo_eats?serverTimezone=Australia/Adelaide&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123123
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
r_eats:
  path: D:\pic\img\
